/**
 * The proofs themselves — generated with the published keys, and verified.
 *
 * Every other circuit suite stops at the witness: `calculateWitness` then
 * `checkConstraints`, which answers "is the R1CS satisfied by this assignment".
 * That is a real question, and 39 rejection tests across the three circuits
 * answer it well. But it is not the question the chain asks.
 *
 * The chain asks whether a 128-byte proof verifies against a registered
 * verifying key, with the public signals in a particular order. Nothing here
 * checked that. A proving key built from a stale `.r1cs`, a verifying key that
 * belongs to a different ceremony, or a prover that reads the public signals in
 * the wrong sequence would all pass the entire existing suite — and every proof
 * they produced would be well-formed, exactly 128 bytes, and rejected on-chain
 * with nothing in the output to say why. That is not hypothetical: it is the
 * shape of the QAP-reduction bug this project already shipped once.
 *
 * So this file proves and verifies for real, with the canonical `.zkey` and the
 * canonical verifying key, and then checks the three things a witness test
 * cannot see:
 *
 *   1. the proof verifies at all,
 *   2. a tampered public signal is rejected,
 *   3. the public signals come out in the order `SIGNAL_LAYOUT` declares.
 *
 * Measured cost: about four seconds for all three circuits.
 *
 * # Why the library and not the CLI
 *
 * `snarkjs groth16 verify` prints `[ERROR] snarkJS: Invalid proof` and then
 * **exits 0** — measured. A test shelling out and checking the exit status would
 * pass on a proof that does not verify, which is precisely the failure this file
 * exists to catch. The library returns a boolean and cannot be misread that way.
 *
 * One consequence: snarkjs leaves worker handles open after proving, so Node
 * does not exit on its own once these tests finish. `.mocharc.json` sets
 * `exit: true` for that reason — without it the whole suite hangs after the last
 * assertion passes. Measured: the same script exits immediately with an explicit
 * `process.exit(0)` and never otherwise.
 */
import fs from "fs";

import { expect } from "chai";
import * as snarkjs from "snarkjs";
import type { Groth16Proof, PublicSignals } from "snarkjs";

import { CIRCUITS, SIGNAL_LAYOUT, signalName } from "../scripts/lib/circuits";
import { artifacts, fixtures, rel } from "../scripts/lib/paths";
import { strict } from "./helpers/artifacts";

/** What one circuit needs before it can be proved. */
interface Inputs {
    zkey: string;
    wtns: string;
    vk: snarkjs.CircuitSignals;
    sym: string;
}

/**
 * Load a circuit's proving inputs, or explain why they are absent.
 *
 * The `.wtns` is gitignored and regenerated by `make-fixture.ts`; the `.zkey`
 * and verifying key come from the ceremony. A developer checkout may have none
 * of them, so this skips — except under `CIRCUITS_REQUIRE_ARTIFACTS`, where a
 * missing artifact is the failure it would be in CI.
 */
function load(circuit: string, ctx: Mocha.Context): Inputs | undefined {
    const { zkey, vkJson, sym } = artifacts(circuit);
    const { wtns } = fixtures(circuit);

    const missing = [zkey, vkJson, sym, wtns].filter((p) => !fs.existsSync(p));
    if (missing.length > 0) {
        const message =
            `${circuit}: cannot prove — missing ${missing.map(rel).join(", ")}. ` +
            `Run 'pnpm build-all' and 'pnpm fixture ${circuit}'.`;
        if (strict()) {
            throw new Error(
                `${message}\nCIRCUITS_REQUIRE_ARTIFACTS is set, so this is a failure ` +
                    `rather than a skip — an unproved circuit is not a verified one.`
            );
        }
        console.log(`  ⚠  ${message}`);
        ctx.skip();
    }

    return { zkey, wtns, sym, vk: JSON.parse(fs.readFileSync(vkJson, "utf8")) };
}

/**
 * The public signal names Circom actually emitted, read from the symbol table.
 *
 * `build/<circuit>.sym` lists one signal per line as
 * `index,witness_index,component,name`, in witness order. The first `n` are the
 * public ones. This is the compiler's own account of the layout, which is what
 * makes it worth comparing against the hand-written table.
 */
function symbolOrder(symPath: string, count: number): string[] {
    return fs
        .readFileSync(symPath, "utf8")
        .split("\n")
        .filter((line) => line.trim().length > 0)
        .slice(0, count)
        .map((line) => line.split(",")[3].replace(/^main\./, ""));
}

describe("Proof generation and verification", function () {
    // Proving transfer touches a 16 MB proving key; the default 120s is enough
    // locally but leaves no headroom on a slower CI runner.
    this.timeout(180_000);

    for (const circuit of CIRCUITS) {
        describe(circuit, function () {
            let inputs: Inputs | undefined;
            let proof: Groth16Proof;
            let publicSignals: PublicSignals;

            before(async function () {
                inputs = load(circuit, this);
                if (!inputs) return;

                const result = await snarkjs.groth16.prove(inputs.zkey, inputs.wtns);
                proof = result.proof;
                publicSignals = result.publicSignals;
            });

            it("the proof verifies against the published verifying key", async function () {
                if (!inputs) return this.skip();

                expect(await snarkjs.groth16.verify(inputs.vk, publicSignals, proof)).to.equal(
                    true,
                    `${circuit}: a proof made with the canonical proving key did not verify ` +
                        `against the canonical verifying key — the two are from different ceremonies, ` +
                        `or the prover and verifier disagree about the circuit`
                );
            });

            it("has the public signal count the verifying key declares", function () {
                if (!inputs) return this.skip();

                expect(publicSignals.length).to.equal(
                    SIGNAL_LAYOUT[circuit].length,
                    `${circuit}: proved with ${publicSignals.length} public signals where the ` +
                        `layout declares ${SIGNAL_LAYOUT[circuit].length}`
                );
            });

            it("emits the public signals in the order SIGNAL_LAYOUT declares", function () {
                if (!inputs) return this.skip();

                const expected = SIGNAL_LAYOUT[circuit].map(signalName);
                const actual = symbolOrder(inputs.sym, expected.length);

                expect(actual).to.deep.equal(
                    expected,
                    `${circuit}: the compiler's symbol table and SIGNAL_LAYOUT disagree about ` +
                        `which signals are public, or about their order. A prover that trusts the ` +
                        `table would produce proofs that never verify.`
                );
            });

            it("rejects a proof whose public signals were tampered with", async function () {
                if (!inputs) return this.skip();

                // Every position, not just the first: a verifier that ignored one
                // signal would still pass a single-position check, and which
                // position is load-bearing differs per circuit.
                for (let i = 0; i < publicSignals.length; i++) {
                    const tampered = [...publicSignals];
                    tampered[i] = (BigInt(tampered[i]) + 1n).toString();

                    expect(await snarkjs.groth16.verify(inputs.vk, tampered, proof)).to.equal(
                        false,
                        `${circuit}: altering public signal ${i} ` +
                            `(${signalName(SIGNAL_LAYOUT[circuit][i])}) did not invalidate the proof`
                    );
                }
            });
        });
    }
});
