/**
 * Private-input freedom scan.
 *
 * A sound spend circuit lets exactly one private witness satisfy a given public
 * statement, up to inputs that are free by design (a dummy slot, a change note
 * that does not exist). The spending-key bug was a failure of this property:
 * `k + l` satisfied the same statement as `k` under another nullifier.
 *
 * The scan perturbs each private input of a valid witness, one at a time and
 * one perturbation at a time, with every public input held fixed. Whatever
 * still satisfies the constraints is "free". A test then asserts the free set
 * equals its explicit whitelist, so a new free input is a failure.
 */
import type { WasmTester } from "circom_tester";

/** BN254 scalar field modulus. */
export const FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;

/** Order of the Baby JubJub subgroup generated by Base8. */
export const BABYJUB_SUBORDER =
    2736030358979909402780800718157159386076813972158567259200215660948447373041n;

export interface Perturbation {
    name: string;
    apply: (v: bigint) => bigint;
}

/** Aliases of the algebra in use: ±1, the subgroup order, the bit-width edges. */
export const PERTURBATIONS: readonly Perturbation[] = [
    { name: "+1", apply: (v) => (v + 1n) % FIELD },
    { name: "-1", apply: (v) => (v + FIELD - 1n) % FIELD },
    { name: "+l", apply: (v) => (v + BABYJUB_SUBORDER) % FIELD },
    { name: "=0", apply: () => 0n },
    { name: "=2^252", apply: () => 1n << 252n },
    { name: "=2^253-1", apply: () => (1n << 253n) - 1n },
    { name: "=p-1", apply: () => FIELD - 1n },
];

type Input = Record<string, any>;

/** Leaf paths of `input` whose top-level name is not public: `spending_keys[1]`, `input_path_elements[0][3]`. */
export function privateLeaves(input: Input, publicNames: readonly string[]): string[] {
    const out: string[] = [];
    const walk = (v: unknown, p: string) => {
        if (Array.isArray(v)) v.forEach((e, i) => walk(e, `${p}[${i}]`));
        else out.push(p);
    };
    for (const [name, v] of Object.entries(input)) {
        if (!publicNames.includes(name)) walk(v, name);
    }
    return out;
}

function readLeaf(input: Input, path: string): bigint {
    return BigInt(String(indices(path).reduce<any>((v, i) => v[i], input)));
}

/** A deep copy of `input` with the leaf at `path` replaced. */
export function withLeaf(input: Input, path: string, value: bigint): Input {
    const copy = JSON.parse(JSON.stringify(input));
    const idx = indices(path);
    let cur: any = copy;
    for (const i of idx.slice(0, -1)) cur = cur[i];
    cur[idx[idx.length - 1]] = value.toString();
    return copy;
}

function indices(path: string): (string | number)[] {
    const [name, ...rest] = path.split("[");
    return [name, ...rest.map((s) => Number(s.replace("]", "")))];
}

async function satisfies(circuit: WasmTester, input: Input): Promise<boolean> {
    try {
        const w = await circuit.calculateWitness(input, true);
        await circuit.checkConstraints(w);
        return true;
    } catch {
        return false;
    }
}

/**
 * Every private leaf that stays satisfiable under some perturbation, mapped to
 * the perturbations that survive. `input` must itself satisfy the circuit.
 */
export async function scanFreedom(
    circuit: WasmTester,
    input: Input,
    publicNames: readonly string[]
): Promise<Map<string, string[]>> {
    if (!(await satisfies(circuit, input)))
        throw new Error("the base input must satisfy the circuit");
    const free = new Map<string, string[]>();
    for (const path of privateLeaves(input, publicNames)) {
        const original = readLeaf(input, path);
        for (const p of PERTURBATIONS) {
            const value = p.apply(original);
            if (value === original) continue;
            if (await satisfies(circuit, withLeaf(input, path, value))) {
                free.set(path, [...(free.get(path) ?? []), p.name]);
            }
        }
    }
    return free;
}

/** `free` as sorted "path: perturbations" lines, for assertion messages. */
export function describeFreedom(free: Map<string, string[]>): string {
    return [...free.entries()]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([path, ps]) => `${path}: ${ps.join(" ")}`)
        .join("\n");
}
