pragma circom 2.0.0;

include "./poseidon_wrapper.circom";
include "./merkle_tree.circom";
include "../node_modules/circomlib/circuits/babyjub.circom";
include "../node_modules/circomlib/circuits/comparators.circom";

// Order of the Baby JubJub subgroup generated by Base8.
function babyjub_suborder() {
    return 2736030358979909402780800718157159386076813972158567259200215660948447373041;
}

// Note commitment: Poseidon(value, asset_id, owner_pubkey, blinding).
template NoteCommitment() {
    signal input value;
    signal input asset_id;
    signal input owner_pubkey;
    signal input blinding;
    signal output commitment;

    component hasher = Poseidon4();
    hasher.inputs[0] <== value;
    hasher.inputs[1] <== asset_id;
    hasher.inputs[2] <== owner_pubkey;
    hasher.inputs[3] <== blinding;

    commitment <== hasher.out;
}

// Nullifier: Poseidon(commitment, spending_key).
template Nullifier() {
    signal input commitment;
    signal input spending_key;
    signal output nullifier;

    component hasher = Poseidon2();
    hasher.inputs[0] <== commitment;
    hasher.inputs[1] <== spending_key;

    nullifier <== hasher.out;
}

// Owner public key (Ax) of a canonical spending key.
//
// BabyPbk takes any key below 2^253, but Base8 generates a subgroup of order l:
// k, k + l, … derive the same owner key — the same note — while the nullifier
// Poseidon(commitment, key) differs for each, so one note could be spent several
// times. The key must therefore be below l. BabyPbk's own Num2Bits(253) bounds
// it first, which keeps LessThan's internal sum in range.
template SpendingKeyOwner() {
    signal input spending_key;
    signal output owner_pubkey;

    component pbk = BabyPbk();
    pbk.in <== spending_key;

    component canonical = LessThan(252);
    canonical.in[0] <== spending_key;
    canonical.in[1] <== babyjub_suborder();
    canonical.out === 1;

    owner_pubkey <== pbk.Ax;
}

// A note being spent: who owns it, which tree it sits in and what spending it
// reveals. The caller decides what to do with `root` and
// `nullifier`: assert them, or leave them free for a dummy input.
template SpentNote(tree_depth) {
    signal input value;
    signal input asset_id;
    signal input blinding;
    signal input spending_key;
    signal input path_elements[tree_depth];
    signal input path_index[tree_depth];
    signal output root;
    signal output nullifier;

    component owner = SpendingKeyOwner();
    owner.spending_key <== spending_key;

    component note = NoteCommitment();
    note.value <== value;
    note.asset_id <== asset_id;
    note.owner_pubkey <== owner.owner_pubkey;
    note.blinding <== blinding;

    component membership = MerkleTreeVerifier(tree_depth);
    membership.leaf <== note.commitment;
    for (var i = 0; i < tree_depth; i++) {
        membership.path_elements[i] <== path_elements[i];
        membership.path_index[i] <== path_index[i];
    }
    root <== membership.root;

    component revealed = Nullifier();
    revealed.commitment <== note.commitment;
    revealed.spending_key <== spending_key;
    nullifier <== revealed.nullifier;
}
